- 1.1.16+202510301932
- _NAME: MX Keys S
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight-timed, led_control,
    led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, reprogrammable-keys, persistent-remappable-keys, crown-smooth, divert-crown,
    divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B37800000000
  _sensitive: {change-host: false, disable-keyboard-keys: false, divert-keys: true, fn-swap: false}
  _unitId: 176F1A4C
  backlight: 1
  backlight_duration_hands_in: 30
  backlight_duration_hands_out: 30
  backlight_duration_powered: 300
  backlight_level: 2
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 111: 0, 199: 0, 200: 0, 226: 0, 227: 0, 228: 1, 229: 1, 230: 1, 231: 0, 232: 0, 233: 0, 234: 0, 259: 0, 264: 1, 266: 1, 284: 1}
  fn-swap: true
  multiplatform: 0
- _NAME: Wireless Mouse MX Master 2S
  _absent: [hi-res-scroll, lowres-scroll-mode, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed,
    dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed,
    led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth,
    divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B01940690000
  _sensitive: {divert-keys: false, gesture2-divert: false, gesture2-gestures: false, reprogrammable-keys: false, scroll-ratchet: false, smart-shift: false}
  _unitId: 12FA2359
  change-host: null
  divert-keys: {82: 0, 83: 1, 86: 1, 195: 0, 196: 0}
  dpi: 1000
  gesture2-divert: {46: false}
  gesture2-gestures: {45: true, 46: true}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 82}
  scroll-ratchet: 2
  smart-shift: 20
- _NAME: 'Wireless Mouse  '
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: '00000000'
  _unitId: '00000000'
  _wpid: '4091'
  divert-keys: {82: 0}
  dpi: 1000
  lowres-scroll-mode: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}
